name: pomodoro_timer
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  http: ^0.13.5
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  flow_builder: ^0.0.9
  material_design_icons_flutter: ^6.0.7096
  fluttertoast: ^8.2.1
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.5.0
  persistent_bottom_nav_bar_v2: ^4.2.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^4.0.0+1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
