// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRPeW_kFBP4u8fVHIrk6ObJfdUhsWFtGo',
    appId: '1:284193916384:web:83671f2fc1373acf761785',
    messagingSenderId: '284193916384',
    projectId: 'pomodoro-7fe6b',
    authDomain: 'pomodoro-7fe6b.firebaseapp.com',
    storageBucket: 'pomodoro-7fe6b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV32lrreyaDKrjDIh8_5vmAmQU8N3BxUA',
    appId: '1:284193916384:android:6faf9cb196334b46761785',
    messagingSenderId: '284193916384',
    projectId: 'pomodoro-7fe6b',
    storageBucket: 'pomodoro-7fe6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARtPXXf9ax-YlL2ZFRf__SDiQeHaW3ReM',
    appId: '1:284193916384:ios:4b88749a8bacec8f761785',
    messagingSenderId: '284193916384',
    projectId: 'pomodoro-7fe6b',
    storageBucket: 'pomodoro-7fe6b.appspot.com',
    iosClientId: '284193916384-si5ouue5kibsvmt97a5set10jh8j7180.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoroTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARtPXXf9ax-YlL2ZFRf__SDiQeHaW3ReM',
    appId: '1:284193916384:ios:4b88749a8bacec8f761785',
    messagingSenderId: '284193916384',
    projectId: 'pomodoro-7fe6b',
    storageBucket: 'pomodoro-7fe6b.appspot.com',
    iosClientId: '284193916384-si5ouue5kibsvmt97a5set10jh8j7180.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoroTimer',
  );
}
